/**
 * ============================================================
 *  PORTFOLIO CONFIGURATION — DO NOT EDIT THIS FILE
 *
 *  Edit  portfolio.config.yaml  instead.
 *  Run   pnpm check-config  to validate before deploying.
 * ============================================================
 */

import type { ColorPreset, PresetPalette } from '@/lib/themes';
import rawConfigYaml from '../portfolio.config.yaml';

const rawConfig = rawConfigYaml as unknown as {
  name: string;
  title: string;
  tagline: string;
  email: string;
  phone?: string;
  location: string;
  avatarUrl: string;
  resumeUrl: string;
  resumeFileName: string;
  openToWork: boolean;
  defaultTheme: string;
  colorPreset: string;
  siteMode?: string;
  resumeTheme?: { twoColumn?: string; classic?: string };
  customColors?: PresetPalette;
  social: Record<string, string>;
  sections: { id: string; show: boolean }[];
  about: string;
  stats: { label: string; value: number; prefix?: string; suffix?: string }[];
  skills: { category: string; items: string[] }[];
  experience: {
    company: string;
    role: string;
    period: string;
    description: string;
    highlights?: string[];
  }[];
  projects: {
    name: string;
    description: string;
    tags: string[];
    liveUrl: string;
    repoUrl: string;
    featured: boolean;
  }[];
  education: { institution: string; degree: string; period: string }[];
  certifications: {
    title: string;
    issuer: string;
    date: string;
    credentialUrl: string;
    badgeUrl: string;
    tags: string[];
  }[];
  publications: {
    title: string;
    authors: string;
    venue: string;
    year: string;
    url: string;
    type: string;
    tags: string[];
  }[];
  testimonials: {
    name: string;
    title: string;
    company: string;
    relationship: string;
    quote: string;
    photoUrl: string;
  }[];
  primaryColor?: string;
  siteUrl?: string;
  showPoweredBy?: boolean;
  contactFormEndpoint?: string;
  contactHeading?: string;
  contactTitle?: string;
  contactDescription?: string;
  analytics?: {
    goatcounterCode?: string;
  };
  blog?: {
    enabled?: boolean;
    title?: string;
    description?: string;
  };
  defaultLanguage: string;
  languages: { code: string; label: string }[];
  [locale: string]: any;
};

export type SectionId =
  | 'about'
  | 'stats'
  | 'skills'
  | 'languages'
  | 'experience'
  | 'projects'
  | 'education'
  | 'certifications'
  | 'publications'
  | 'testimonials'
  | 'contact';

export interface SectionEntry {
  id: SectionId;
  show: boolean;
}

export interface Language {
  name: string;
  level: string;
}

export interface Certification {
  title: string;
  issuer: string;
  date: string;
  credentialUrl: string;
  badgeUrl: string;
  tags: string[];
}

export interface Stat {
  label: string;
  value: number;
  prefix?: string;
  suffix?: string;
}

export interface Experience {
  company: string;
  role: string;
  period: string;
  description: string;
  highlights?: string[];
}

export interface Project {
  name: string;
  description: string;
  tags: string[];
  liveUrl: string;
  repoUrl: string;
  featured: boolean;
}

export interface Education {
  institution: string;
  degree: string;
  period: string;
}

export interface Publication {
  title: string;
  authors: string;
  venue: string;
  year: string;
  url: string;
  type: string;
  tags: string[];
}

export interface Testimonial {
  name: string;
  title: string;
  company: string;
  relationship: string;
  quote: string;
  photoUrl: string;
}

export interface ResumeTheme {
  twoColumn: ColorPreset;
  classic: ColorPreset;
}

// ── i18n types ──────────────────────────────────────────────────

export interface LanguageEntry {
  code: string;
  label: string;
}

export interface LocaleUI {
  about: string;
  stats: string;
  skills: string;
  languages: string;
  experience: string;
  projects: string;
  education: string;
  certifications: string;
  publications: string;
  testimonials: string;
  contact: string;
  more: string;
  blog: string;
  resume: string;
  downloadResume: string;
  openToOpportunities: string;
  viewMyWork: string;
  viewResume: string;
  scrollDown: string;
  aboutMe: string;
  aboutHeading: string;
  toolbox: string;
  skillsTitle: string;
  careerPath: string;
  experienceHeading: string;
  featuredWork: string;
  projectsHeading: string;
  viewProject: string;
  sourceCode: string;
  educationHeading: string;
  certificationsHeading: string;
  publicationsHeading: string;
  conference: string;
  journal: string;
  preprint: string;
  testimonialsHeading: string;
  getInTouch: string;
  contactTitle: string;
  contactDescription: string;
  yourName: string;
  yourEmail: string;
  message: string;
  messagePlaceholder: string;
  sendMessage: string;
  sending: string;
  openInEmailApp: string;
  orEmailDirectly: string;
  messageSent: string;
  somethingWentWrong: string;
  sharePortfolio: string;
  builtWith: string;
  forkAndMakeYours: string;
  whatsNew: string;
  shareTitle: string;
  copyLink: string;
  linkCopied: string;
  shareOn: string;
  copySectionLink: string;
  copied: string;
  switchLanguage: string;
  portfolio: string;
  twoColumn: string;
  classic: string;
  share: string;
  savePdf: string;
  summary: string;
  ghStats: string;
  ghStatsEyebrow: string;
  statsEyebrow: string;
  educationEyebrow: string;
  bookChapter: string;
  workshop: string;
  communication: string;
  starsEarned: string;
  followers: string;
  publicRepos: string;
  viewProfile: string;
  topLanguages: string;
  rateLimited: string;
  opensEmailClient: string;
}

export interface LocaleContent {
  name: string;
  title: string;
  tagline: string;
  location: string;
  phone?: string;
  about: string;
  resumeUrl: string;
  resumeFileName: string;
  stats: Stat[];
  languages: Language[];
  skills: { category: string; items: string[] }[];
  experience: Experience[];
  projects: Project[];
  education: Education[];
  certifications: Certification[];
  publications: Publication[];
  testimonials: Testimonial[];
  ui: LocaleUI;
}

export const config = {
  ...rawConfig,
  colorPreset: rawConfig.colorPreset as ColorPreset,
  defaultTheme: rawConfig.defaultTheme as 'system' | 'light' | 'dark',
  siteMode: (rawConfig.siteMode ?? 'portfolio') as 'landing' | 'portfolio',
  sections: rawConfig.sections as SectionEntry[],
  stats: (rawConfig.stats ?? []) as Stat[],
  certifications: (rawConfig.certifications ?? []) as Certification[],
  publications: (rawConfig.publications ?? []) as Publication[],
  testimonials: (rawConfig.testimonials ?? []) as Testimonial[],
  siteUrl: rawConfig.siteUrl ?? '',
  showPoweredBy: rawConfig.showPoweredBy ?? false,
  contactFormEndpoint: rawConfig.contactFormEndpoint ?? '',
  contactHeading: rawConfig.contactHeading ?? '',
  contactTitle: rawConfig.contactTitle ?? '',
  contactDescription: rawConfig.contactDescription ?? '',
  analytics: {
    goatcounterCode: rawConfig.analytics?.goatcounterCode ?? '',
  },
  blog: {
    enabled: rawConfig.blog?.enabled ?? false,
    title: rawConfig.blog?.title ?? 'Blog',
    description: rawConfig.blog?.description ?? '',
  },
  primaryColor: rawConfig.primaryColor ?? '',
  customColors: rawConfig.customColors,
  resumeTheme: {
    twoColumn: (rawConfig.resumeTheme?.twoColumn ??
      rawConfig.colorPreset) as ColorPreset,
    classic: (rawConfig.resumeTheme?.classic ??
      rawConfig.colorPreset) as ColorPreset,
  } as ResumeTheme,
  defaultLanguage: rawConfig.defaultLanguage ?? 'en',
  languages: (rawConfig.languages ?? [{ code: 'en', label: 'English' }]) as LanguageEntry[],
};

export function getContent(locale: string): LocaleContent {
  const raw = rawConfigYaml as unknown as Record<string, any>;
  return raw[locale] ?? raw[rawConfig.defaultLanguage ?? 'en'];
}
